### ISSUE TITLE
file_url base is "file" instead of "files"

### ISSUE THREAD

**Issue by khoran** [developmentforpeople/dfp_external_storage#6]
The default File doctype uses "/files" for the base of the `file_url` field. But DFPExternalFile uses "/file". This seems to work fine most of the time. But I just encountered a case where it is a problem. I had a Sales Order with two attachments. It was canceled and I was trying to amend it. Part of that process is transferring the attachments to the new, amended, Sales Order. At some point the File.validate function is called, which calls File.validate_file_url, which contains the following:

```
def validate_file_url(self):
		if self.is_remote_file or not self.file_url:
			return

		if not self.file_url.startswith(("/files/", "/private/files/")):
			# Probably an invalid URL since it doesn't start with http either
			frappe.throw(
				_("URL must start with http:// or https://"),
				title=_("Invalid URL"),
			)
```

In particular, it checks that the `file_url` field starts with either "/files" or "/private/files". The first one fails since it starts with "/file". Now it seems like this check should never even happen because of the `is_remote_file` check at the beginning. But somehow I got that exact error message, ie, "URL must start with http:// or https://" ( which seems like a terrible error message since that's not what it's checking, but that's a different issue...). I don't have an explanation for that part. I suspect it is creating a new File (still local) by copying the fields from the DFPExternalFile. Thus it's not yet remote, but still has the invalid `file_url` data.

Is it possible to just change the prefix  to "/files"?

**Comment by developmentforpeople** [comment]
Hi again @khoran, thinking about it, as you say, the first line in validate_file_url() function should do the work. It is overrided trough our hook:
/apps/dfp_external_storage/dfp_external_storage/hooks.py
```py
override_doctype_class = {
	"File": "dfp_external_storage.dfp_external_storage.doctype.dfp_external_storage.dfp_external_storage.DFPExternalStorageFile",
}
```
/apps/dfp_external_storage/dfp_external_storage/dfp_external_storage/doctype/dfp_external_storage/dfp_external_storage.py
```py
class DFPExternalStorageFile(File):
	def __init__(self, *args, **kwargs):
		super(DFPExternalStorageFile, self).__init__(*args, **kwargs)

	@property
	def is_remote_file(self):
		return True if self.dfp_external_storage_s3_key else super(DFPExternalStorageFile, self).is_remote_file
```
I would put a breakpoint or print within ```def is_remote_file(self)``` to figure out what it is happening and why it is not setting the file as remote 🙂. Please tell me if you find something about it. I will check the same when I have more time ;)

**Comment by khoran** [comment]
Here is the function that transfers over the attachments: 
```
def copy_attachments_from_amended_from(self):
		"""Copy attachments from `amended_from`"""
		from frappe.desk.form.load import get_attachments

		# loop through attachments
		for attach_item in get_attachments(self.doctype, self.amended_from):

			# save attachments to new doc
			_file = frappe.get_doc(
				{
					"doctype": "File",
					"file_url": attach_item.file_url,
					"file_name": attach_item.file_name,
					"attached_to_name": self.name,
					"attached_to_doctype": self.doctype,
					"folder": "Home/Attachments",
				}
			)
			_file.save()
```
This is called from the `before_insert` hook.

So it creates a new file by copying the value of `file_url` from the old file. Perhaps you know better than I, when it creates this new file, does it start off local and then this plugin notices it's folder and makes it remote? Or is it immediately created as a remote file? If the former, then I think the problem occurs during that window when the new file is still local, but has the `file_url` of a remote file, which is invalid. 

It seems like, since DFP_External_Storage only overrides the hooks `before_save` and `on_update`, that the above function is running first, before you have a chance to make it remote. 

Here is the stack trace of the error:
```
13:04:58 web.1            | Traceback (most recent call last):
13:04:58 web.1            |   File "apps/frappe/frappe/app.py", line 94, in application
13:04:58 web.1            |     response = frappe.api.handle()
13:04:58 web.1            |   File "apps/frappe/frappe/api.py", line 54, in handle
13:04:58 web.1            |     return frappe.handler.handle()
13:04:58 web.1            |   File "apps/frappe/frappe/handler.py", line 47, in handle
13:04:58 web.1            |     data = execute_cmd(cmd)
13:04:58 web.1            |   File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
13:04:58 web.1            |     return frappe.call(method, **frappe.form_dict)
13:04:58 web.1            |   File "apps/frappe/frappe/__init__.py", line 1610, in call
13:04:58 web.1            |     return fn(*args, **newargs)
13:04:58 web.1            |   File "apps/frappe/frappe/desk/form/save.py", line 28, in savedocs
13:04:58 web.1            |     doc.save()
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 305, in save
13:04:58 web.1            |     return self._save(*args, **kwargs)
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 327, in _save
13:04:58 web.1            |     return self.insert()
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 280, in insert
13:04:58 web.1            |     self.copy_attachments_from_amended_from()
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 382, in copy_attachments_from_amended_from
13:04:58 web.1            |     _file.save()
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 305, in save
13:04:58 web.1            |     return self._save(*args, **kwargs)
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 327, in _save
13:04:58 web.1            |     return self.insert()
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 253, in insert
13:04:58 web.1            |     self.run_method("before_insert")
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 914, in run_method
13:04:58 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 1264, in composer
13:04:58 web.1            |     return composed(self, method, *args, **kwargs)
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 1246, in runner
13:04:58 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
13:04:58 web.1            |   File "apps/frappe/frappe/model/document.py", line 911, in fn
13:04:58 web.1            |     return method_object(*args, **kwargs)
13:04:58 web.1            |   File "apps/frappe/frappe/core/doctype/file/file.py", line 70, in before_insert
13:04:58 web.1            |     self.save_file(content=self.get_content())
13:04:58 web.1            |   File "apps/frappe/frappe/core/doctype/file/file.py", line 459, in get_content
13:04:58 web.1            |     self.validate_file_url()
13:04:58 web.1            |   File "apps/frappe/frappe/core/doctype/file/file.py", line 175, in validate_file_url
13:04:58 web.1            |     frappe.throw(
13:04:58 web.1            |   File "apps/frappe/frappe/__init__.py", line 528, in throw
13:04:58 web.1            |     msgprint(
13:04:58 web.1            |   File "apps/frappe/frappe/__init__.py", line 496, in msgprint
13:04:58 web.1            |     _raise_exception()
13:04:58 web.1            |   File "apps/frappe/frappe/__init__.py", line 445, in _raise_exception
13:04:58 web.1            |     raise raise_exception(msg)
13:04:58 web.1            | frappe.exceptions.ValidationError: URL must start with http:// or https://
```
Perhaps the `copy_attachments_from_amended_from` could be overriden? Or else the `validate_file_url` function?

**Comment by developmentforpeople** [comment]
Resolved

**Comment by khoran** [comment]
I'm still experiencing the same issue using the latest 'develop' branch. You commented that it was resolved, what was changed?

**Comment by developmentforpeople** [comment]
Answered [here](https://github.com/developmentforpeople/dfp_external_storage/issues/12#issuecomment-1861754170)

**Comment by khoran** [comment]
This issue is not the same as the report not working. The issue remains even on the fix-get-content branch. 
To re-create this issue, find a submittable document (ie, a Sales Order), with an attached file. Cancel it, then amend it. When you then try to save the amended document, you will get the error  "URL must start with http:// or https://".

**Comment by developmentforpeople** [comment]
Sorry @khoran you are right! Resolved in "develop" with this commit 😉: https://github.com/developmentforpeople/dfp_external_storage/commit/10c2df5c45a0108a256106fed83fd464d10b26fd
Have good days with your family and friends!

**Comment by khoran** [comment]
Great, that works. Thank you.
